{{- if .Values.benji.api.enabled  }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tuple . "api" | include "benji.fullname" }}
  annotations:
    checksum/config: {{ .Values.benji.configuration | toYaml | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: benji
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.benji.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "benji.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "benji.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ tuple . "" | include "benji.fullname" }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: benji
          image: "{{ .Values.benji.image.registry }}/{{ .Values.benji.image.repository }}:{{ .Values.benji.image.tag }}"
          imagePullPolicy: {{ .Values.benji.image.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - benji
            - rest-api
            - --threads={{ .Values.benji.api.threadsPerReplica }}
            - --bind-address=0.0.0.0
            - --bind-port={{ .Values.benji.api.port }}
          ports:
            - name: api
              containerPort: {{ .Values.benji.api.port }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: "{{ .Values.timeZone }}"
            - name: BENJI_EXPERIMENTAL
              value: "1"
          volumeMounts:
            - name: benji-config
              mountPath: /benji/etc
            - name: tz-config
              mountPath: /etc/localtime
{{- with .Values.benji.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
      hostNetwork: false
      volumes:
        - name: benji-config
          secret:
            secretName: {{ tuple . "" | include "benji.fullname" }}
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/{{ .Values.timeZone }}
{{- with .Values.benji.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.benji.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.benji.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
