{{- if .Values.ceph.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.ceph.configMapName }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: benji
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ceph.conf: |
{{ include "benji.ceph-conf" . | indent 4 }}
{{- end }}
