#!/usr/bin/env bash

exec > >(logger -t "benji-backup") 2>&1

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
if [ $# != 1 ]; then
    echo "usage: $0 LABEL-SELECTOR" 1>&2
    exit 1
fi
LABEL_SELECTOR="$1"

. defaults.sh
. prometheus.sh
. metrics.sh
. tryCatch.sh
. common.sh
. ceph.sh

# Get a list of persistent volumes
PVS=$(kubectl get pvc --all-namespaces -l "$LABEL_SELECTOR" -o json | jq -r '
	.items | map(select(.metadata.annotations."volume.beta.kubernetes.io/storage-provisioner" as $prov | ["rook.io/block"] | index($prov))
               | .spec.volumeName)
               | .[]
')

for pv in $PVS
do
	set -- $(kubectl get pv "$pv" -o jsonpath='{.spec.claimRef.namespace}{" "}{.spec.claimRef.name}{" "}{.spec.flexVolume.options.pool}{" "}{.spec.flexVolume.options.image}')
	PVC_NAMESPACE="$1"
	PVC_NAME="$2"
	CEPH_POOL="$3"
	CEPH_IMAGE="$4"
	NAME="$PVC_NAMESPACE/$PVC_NAME"

	benji::backup::ceph "$NAME" "$CEPH_POOL" "$CEPH_IMAGE" \
            "benji-backup.me/instance=${BENJI_INSTANCE:-benji-k8s}" \
            "benji-backup.me/ceph-pool=$CEPH_POOL" \
            "benji-backup.me/ceph-image=$CEPH_IMAGE" \
            "benji-backup.me/k8s-pvc-namespace=$PVC_NAMESPACE" \
            "benji-backup.me/k8s-pvc-name=$PVC_NAME" \
            "benji-backup.me/k8s-pv=$pv"
done

echo
io::prometheus::ExportAsText | grep -v '^#'
io::prometheus::Push job=benji gateway="$PROM_PUSH_GATEWAY"
