#!/usr/bin/env bash

exec > >(logger -i -t "benji-versions-status") 2>&1

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

. common.sh
. prometheus.sh
. hooks.sh

benji::prometheus::versions_status
benji::prometheus::push
