#!/usr/bin/env bash

exec > >(logger -i -t "benji-versions-status") 2>&1

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

. defaults.sh
. prometheus.sh
. metrics.sh
. tryCatch.sh
. common.sh

benji::versions_status
benji::push_metrics
