#!/bin/bash
set -xeo pipefail
id -a
pwd

REPO_ROOT="$(git rev-parse --show-toplevel)"
if [[ $GIT_PEP440_VERSION_VARIANT ]]; then
    GIT_PEP440_VERSION="$REPO_ROOT/maint-scripts/git-pep440-version-$GIT_PEP440_VERSION_VARIANT"
else
    GIT_PEP440_VERSION_VARIANT=''
    GIT_PEP440_VERSION="$REPO_ROOT/maint-scripts/git-pep440-version"
fi

if [[ $COMMIT_MSG ]]; then
    # Docker Cloud
    BUILD_ENV=docker

    if [[ $GIT_PEP440_VERSION_VARIANT == miniver ]]; then
        # Install pip (globally) which includes setuptools which are needed by
        # git-pep440-version-miniver
        curl https://bootstrap.pypa.io/get-pip.py -o ./get-pip.py
        python3 ./get-pip.py
    fi

    VERSION="$($GIT_PEP440_VERSION)"
    if [[ $VERSION =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]]; then
        BASE_TAG="$VERSION"
    else
        BASE_TAG="$SOURCE_BRANCH"
    fi

    # CWD is directory of the Dockerfile
    cd "$REPO_ROOT"
elif [[ $TRAVIS_COMMIT_MESSAGE ]]; then
    # Travis CI
    BUILD_ENV=travis
    DOCKER_REPO="$(cd $(dirname $DOCKERFILE_PATH) && pwd)"
    DOCKER_REPO="elementalnet/${DOCKER_REPO##*/}"
    SOURCE_BRANCH="$TRAVIS_BRANCH"

    VERSION="$($GIT_PEP440_VERSION)"
    if [[ $VERSION =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]]; then
        BASE_TAG="$VERSION"
        TAG="$VERSION"
    else
        BASE_TAG="$SOURCE_BRANCH"
        TAG="$SOURCE_BRANCH"
    fi
    IMAGE_NAME="$DOCKER_REPO:$TAG"
else
    # Local
    BUILD_ENV=local
    SOURCE_BRANCH="$(git symbolic-ref --short HEAD)"
    DOCKER_REPO="$(cd $(dirname $DOCKERFILE_PATH) && pwd)"
    DOCKER_REPO="elementalnet/${DOCKER_REPO##*/}"

    VERSION="$($GIT_PEP440_VERSION)"
    if [[ $VERSION =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]]; then
        BASE_TAG="$VERSION"
        TAG="$VERSION"
    else
        BASE_TAG="$SOURCE_BRANCH"
        TAG="$SOURCE_BRANCH"
    fi
    IMAGE_NAME="$DOCKER_REPO:$TAG"
fi

# BASE_TAG is only used by derived images
docker build \
  --build-arg BASE_TAG="$BASE_TAG" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
  --build-arg VCS_URL="$(git config --get remote.origin.url)" \
  --build-arg VERSION="$VERSION" \
  -f $DOCKERFILE_PATH \
  -t $IMAGE_NAME .

# Docker Cloud will push $IMAGE_NAME automatically after this script,
# for the Travis CI case push here
if [[ ! $SKIP_DOCKER_PUSH && $BUILD_ENV == travis ]]; then
    docker push "$IMAGE_NAME"
fi

if [[ $VERSION =~ ^[0-9]+\.[0-9]+.[0-9]+$ ]]; then
    docker tag $IMAGE_NAME "$DOCKER_REPO:$VERSION"
    if [[ ! $SKIP_DOCKER_PUSH && ($BUILD_ENV == docker || $BUILD_ENV == travis) ]]; then
        docker push "$DOCKER_REPO:$VERSION"
    fi
fi

if [[ $SOURCE_BRANCH == master ]]; then
    docker tag $IMAGE_NAME "$DOCKER_REPO:latest"
    if [[ ! $SKIP_DOCKER_PUSH && ($BUILD_ENV == docker || $BUILD_ENV == travis) ]]; then
        docker push "$DOCKER_REPO:latest"
    fi
fi

